flask:
    secret_key: minecraft
    debug: True
    ext: True
server:
    address: 192.168.2.105
    port: 1234
minecraft:
    path: C:\Users\bib\AppData\Roaming\.minecraft\bin\launcher.jar
    connection_file: player.txt
    server_file: server.txt
java:
    path: C:\Program Files (x86)\Java\jre7\bin\java.exe
database: sqlite:///database.db
#    path: /usr/bin/java
#    path: /home/bib/.minecraft/launcher.jar
# database: mysql+pymysql://root:bib@localhost/minecraft