server:
    address: 127.0.0.1
    port: 1234
minecraft:
    path: /home/bib/.minecraft/launcher.jar
    connection_file: player.txt
    server_file: server.txt
java:
    path: /usr/bin/java
database: mysql+pymysql://root:bib@localhost/minecraft